#= require jquery
#= require jquery_ujs
#= require jquery-ui/datepicker
#= require jquery-ui/effect-fade
#= require bootstrap
#= require ckeditor/init
#= require ckeditor/config
#= require core
#= require_self
